config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :materials
    resources :lines
    resources :checklists
    resources :working_teams
    resources :intequipments do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :teams
    resources :events
    resources :intlines do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :issues


    # get 'intlines/:id/restore', to: 'intlines#restore', as: 'restore'
    # get '/ok_line', to: 'intlines#restore'

    post '/newEvent', to: 'events#create'

    post '/newHSline', to: 'intlines#create'
    post '/newHsEquipment', to: 'intequipments#create'

    get 'sessions/new'

    root 'static_pages#home'

    get 'users/new'
    get 'users/edit'

    get '/home',    to: 'static_pages#home'
    get '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'



    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    resources :account_activations, only: [:edit]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line.rb
class Line < ApplicationRecord
    belongs_to :team
    # validates :team_id, presence: true
    default_scope -> { order(created_at: :desc) }
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
      @selectedTeam = Team.find_by(id: params[:line][:team_id])
      @line = @selectedTeam.lines.build(line_params)
      if @line.save
          flash[:success] = "line created"
          redirect_to lines_path
      else
          render 'static_pages/home'
      end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
      @line = Line.find(params[:id])
      if @line.update_attributes(line_params)
          flash[:success] = "Line updated"
          redirect_to lines_path
      else
          render 'edit'
      end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
      Line.find(params[:id]).destroy
      flash[:success] = "Line deleted"
      redirect_to lines_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:name, :team_id)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
      <%= f.collection_select :team_id, Team.all, :id, :name, {:prompt => ' Select Team'}, {:class => 'selectpicker'}%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<% provide(:title, "Lines") %>
<div style="padding: 8px;width: 200px;float:right;z-index:1;">
    <%= link_to 'New Line', new_line_path, class: "btn btn-success btn-md" %>
</div>
<table id='async_datatable' class="table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Panel</th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.name %></td>
        <td><%= line.team.name %></td>
        <td>
            <%= link_to '', edit_line_path(line), class:'fa fa-1mx fa-pencil-square-o'  %> | 
            <%= link_to '', line, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-1mx fa-trash-o'  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lines/new.html.erb
<h1>New line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Back', lines_path %>