config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :materials
    resources :lines
    resources :checklists
    resources :working_teams
    resources :intequipments do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :teams
    resources :events
    resources :intlines do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :issues


    # get 'intlines/:id/restore', to: 'intlines#restore', as: 'restore'
    # get '/ok_line', to: 'intlines#restore'

    post '/newEvent', to: 'events#create'

    post '/newHSline', to: 'intlines#create'
    post '/newHsEquipment', to: 'intequipments#create'

    get 'sessions/new'

    root 'static_pages#home'

    get 'users/new'
    get 'users/edit'

    get '/home',    to: 'static_pages#home'
    get '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'



    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    resources :account_activations, only: [:edit]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
	belongs_to :user
	belongs_to :team

	# validates :user_id, presence: true
	# validates :team_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :team
  # default_scope -> { order(created_at: :desc) }
  # validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/intequipment.rb
class Intequipment < ApplicationRecord
	belongs_to :user
	belongs_to :team
	validates :user_id, presence: true
end

app/models/intline.rb
class Intline < ApplicationRecord


    belongs_to :user
    belongs_to :team

    validates :remHS, presence: true
    # validates :lineName, presence: true

  	# default_scope -> { order(created_at: :desc) }
  	# validates :user_id, presence: true
end

app/models/issue.rb
class Issue < ApplicationRecord

	belongs_to :team
	# validates :user_id, presence: true

  	attr_accessor :date_range

  def all_day_issue?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/line.rb
class Line < ApplicationRecord
    belongs_to :team
    # validates :team_id, presence: true
    default_scope -> { order(created_at: :desc) }
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :team
	# validates :team_id, presence: true
	default_scope -> { order(created_at: :desc) }
end

app/models/team.rb
class Team < ApplicationRecord

	has_many :users
	has_many :lines
	has_many :materials
	has_many :events
	has_many :intlines
	has_many :intequipments
	has_many :issues
	has_many :checklists
	has_many :working_teams

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    belongs_to :teams, optional:true
    has_many :events
    has_many :intlines
    has_many :intequipments
    has_many :checklists

    validates :team_id, presence: true
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
                  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email,	presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/working_team.rb
class WorkingTeam < ApplicationRecord
	belongs_to :team
	before_save do
  		self.esaRadar.gsub!(/[\[\]\"]/, "") if attribute_present?("esaRadar")
		self.esaCom.gsub!(/[\[\]\"]/, "") if attribute_present?("esaCom")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "EFDMROR"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/intlines_helper.rb
module IntlinesHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
	def log_in_as(user)
		session[:user_id] = user.id
	end

# Confirms an admin user.
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

# Returns the team of the current user
	def current_team
		Team.find_by(id: current_user.team_id)
	end

# Verify if correct User
	def correct_user
	    @user = User.find(params[:id])
	    unless current_user?(@user)
	        flash[:danger] = "You don't have rights"
			redirect_back_or(root_url)
	    end
	end

# Returns the current logged-in user (if any).
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

# Returns true if the user is logged in, false otherwise.
	def logged_in?
		!current_user.nil?
	end

# Logs out the current user.
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

# Returns true if the given user is the current user.
 	def current_user?(user)
   		user == current_user
 	end

# Redirects to stored location (or to the default).
  	def redirect_back_or(default)
    	redirect_to(session[:forwarding_url] || default)
	    session.delete(:forwarding_url)
	end

# Stores the URL trying to be accessed.
	def store_location
    	session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
    	<div class="alert alert-danger">
      		The form contains <%= pluralize(object.errors.count, "error") %>.
    	</div>
    	<ul>
    		<% object.errors.full_messages.each do |msg| %>
      			<li><%= msg %></li>
    		<% end %>
    	</ul>
  	</div>
<% end %>

app/views/shared/_event_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new event..." %>
    </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="events">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_tablEvent.html.erb
<table id='async_dataEvent' class="table-striped">
  <thead>
    <tr>
      <th>Opened</th>
      <th>Object</th>
      <th>Added by</th>
      <th>Content</th>
	  <th>Panel</th>
    </tr>
  </thead>

  <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.created_at %></td>
          <td><%= event.object %></td>
          <td><%= event.user.name %></td>
          <td><%= event.content %></td>
          <td class="panelDataTable">
              <%= link_to '', edit_event_path(event), class:'fa fa-1mx fa-pencil-square-o' %>
              <%= link_to '', event, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-1mx fa-trash-o' %>
          </td>
        </tr>
      <% end %>
  </tbody>

</table>

app/views/shared/_tableIntequipment.html.erb
<table id='async_dataIntequipment' class="table-striped">
  <thead>
    <tr>
      <th>Opened</th>
      <th>Equipment Name</th>
      <th>Ticket Number</th>
      <th>Note HS</th>
      <th>Added by</th>
      <th>Panel</th>
    </tr>
  </thead>

  <tbody>
      <% @intequipments.each do |intequipment| %>
        <tr>
          <td><%= intequipment.created_at.strftime("[%d-%m-%y][%H:%M]") %></td>
          <td><%= intequipment.equipmentName %></td>
          <td><%= intequipment.ticketN %></td>
          <td><%= intequipment.remHS %></td>
          <td><%= intequipment.user.name %></td>
          <td class="panelDataTable">
              <%= link_to('', restore_intequipment_path(intequipment),class:'fa fa-1mx fa-check') %>
              <%= link_to('', edit_intequipment_path(intequipment), class:'fa fa-1mx fa-pencil-square-o') %>
              <%= link_to('', intequipment, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-1mx fa-trash-o') %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/shared/_tableIntline.html.erb
<table id='async_dataIntline' class="table-striped">
  <thead>
    <tr>
      <th>Opened</th>
      <th>Line Name</th>
      <th>Ticket Number</th>
      <th>Note HS</th>
      <th>Added by</th>
      <th>Panel</th>
    </tr>
  </thead>

  <tbody>
      <% @intlines.each do |intline| %>
        <tr>
          <td><%= intline.created_at.strftime("[%d-%m-%y][%H:%M]") %></td>
          <td><%= intline.lineName %></td>
          <td><%= intline.ticketN %></td>
          <td><%= intline.remHS %></td>
          <td><%= intline.user.name %></td>
          <td class="panelDataTable">
              <%= link_to('', restore_intline_path(intline), class:'fa fa-1mx  fa-check') %>
              <%= link_to('', edit_intline_path(intline), class:'fa fa-1mx  fa-pencil-square-o') %>
              <%= link_to('', intline, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-1mx fa-trash-o') %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.events.count, "event") %></span>