config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :materials
    resources :lines
    resources :checklists
    resources :working_teams
    resources :intequipments do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :teams
    resources :events
    resources :intlines do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :issues


    # get 'intlines/:id/restore', to: 'intlines#restore', as: 'restore'
    # get '/ok_line', to: 'intlines#restore'

    post '/newEvent', to: 'events#create'

    post '/newHSline', to: 'intlines#create'
    post '/newHsEquipment', to: 'intequipments#create'

    get 'sessions/new'

    root 'static_pages#home'

    get 'users/new'
    get 'users/edit'

    get '/home',    to: 'static_pages#home'
    get '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'



    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    resources :account_activations, only: [:edit]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :team
  # default_scope -> { order(created_at: :desc) }
  # validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :logged_in_user, only: [:edit, :update, :create, :destroy, :new, :index]
	before_action :correct_user, only: [:destroy, :edit, :update]

	def index
		respond_to do |format|
		format.html
		format.json { render json: EventsDatatable.new(view_context, current_user) }
	  end
	end

	def new
		@lines = Line.where("team_id = #{current_user.team_id}")
		@event = current_user.events.build
	end

	def create
		@event = current_user.events.build(event_params)
		@event.update_attributes(team_id: current_user.team_id)
		if	@event.save
			flash[:success] = "Event created"
			redirect_to home_path
		else
			render 'static_pages/home'
		end
	end

	def destroy
		Event.find(params[:id]).destroy
    	flash[:success] = "Event deleted"
    	redirect_to request.referrer || root_url
	end

	def edit
		@event = Event.find_by(id: params[:id])
	end

	def update
		@event = Event.find_by(id: params[:id])
		if @event.update_attributes(event_params)
			flash[:success] = "Post updated"
			redirect_to home_path
		else
			render 'edit'
		end
	end

	private

	def event_params
		params.require(:event).permit(:created_at, :content, :object, :userName)
	end

	def correct_user
        @event = current_user.events.find_by(id: params[:id])
        if @event.nil?
            redirect_to root_path
            flash[:danger] = "You don't have rights"
        end
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<% provide(:title, "Events") %>
<div style="padding: 8px;width: 200px;float:right;z-index:1;">
    <%= link_to 'Add Event', new_event_path, class: "btn btn-success btn-md" %>
</div>
<%= content_tag :table, class: "table-striped", role: :datatable, data: { url: events_path(format: :json)} do %>
  <thead>
    <tr>
      <th>Opened</th>
      <th>Object</th>
      <th>Added by</th>
      <th>Content</th>
	  <th>Panel</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
<% end %>
<br>

app/views/events/new.html.erb
<% provide(:title, 'Report Event') %>


<div class="col-md-6">
  <div class="box box-primary">

		<%= form_for @event, url: newEvent_path do |f| %>
		<!-- <%= render 'shared/error_messages', object: f.object %> -->
		  <div class="box-body">
			  <div class="bootstrap-timepicker">
					<div class="form-group">
				  		<label>Time picker</label>
						<div class="input-group">
							<%= f.text_field :created_at, class:"form-control timepicker" %>
							<div class="input-group-addon">
					  			<i class="fa fa-clock-o"></i>
							</div>
				  		</div>
					</div>
			  	</div>

			  	<div class="form-group">
					<label>Line</label>
                    <!-- <%= f.collection_select :id, Line.all, :id, :name, {:prompt => ' Select Line'}%> -->
					<%= f.select :object, Line.all.map(&:name) , {include_blank: true}, class:"form-control select2" %>
			  	</div>

				<div class="form-group">
					<label>Note</label>
					  <div class="box-body pad">
						  <%= f.text_area :content, class:"textarea" %>
					  </div>
			  	</div>

			  	<div class="box-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
			  	</div>
			</div>
		<%end%>
	</div>
</div>