config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :materials
    resources :lines
    resources :checklists
    resources :working_teams
    resources :intequipments do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :teams
    resources :events
    resources :intlines do
        member do
            patch 'close'
            get 'restore'
        end
    end
    resources :issues


    # get 'intlines/:id/restore', to: 'intlines#restore', as: 'restore'
    # get '/ok_line', to: 'intlines#restore'

    post '/newEvent', to: 'events#create'

    post '/newHSline', to: 'intlines#create'
    post '/newHsEquipment', to: 'intequipments#create'

    get 'sessions/new'

    root 'static_pages#home'

    get 'users/new'
    get 'users/edit'

    get '/home',    to: 'static_pages#home'
    get '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'



    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    resources :account_activations, only: [:edit]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/intline.rb
class Intline < ApplicationRecord


    belongs_to :user
    belongs_to :team

    validates :remHS, presence: true
    # validates :lineName, presence: true

  	# default_scope -> { order(created_at: :desc) }
  	# validates :user_id, presence: true
end

app/controllers/intlines_controller.rb
class IntlinesController < ApplicationController
before_action :set_intline, only: [:edit, :restore, :update, :close, :destroy]
before_action :logged_in_user, only: [:edit, :update, :create, :destroy, :new, :index]
before_action :correct_user, only: [:edit, :update, :destroy]

# ========================================================================================== #

def index
    respond_to do |format|
    format.html
    format.json { render json: IntlinesDatatable.new(view_context, current_user) }
  end
end

def new
    @lines = current_team.lines
    if logged_in?
        @intline = current_user.intlines.build
    else
        redirect_to login_path
    end
end

def edit
end

def restore
end

def close
    if @intline.update_attributes(intline_params)
        @intline.update_attributes(closed: true, userOK: current_user.name)
        flash[:success] = "Report line closed"
        redirect_to intlines_path
    else
        render 'restore'
    end
end

def create
    @intline = current_user.intlines.build(intline_params)
    @intline.update_attributes(userHS: current_user.name, team_id: current_user.team_id) #not the final implemetation
    if @intline.save
        flash[:success] = "Report Line created"
        redirect_to root_path
    else
        render 'static_pages/home'
    end
end

def update
    if @intline.update_attributes(intline_params)
        flash[:success] = "Report line updated"
        redirect_to home_path
    else
        render 'edit'
    end
end


def destroy
    @intline.destroy
    flash[:success] = "Report Line deleted"
    redirect_to request.referrer || root_url
end

# ========================================================================================== #

private

  def set_intline
    @intline = Intline.find_by(params[:id])
  end

  def correct_user
      @intline = current_user.intlines.find_by(id: params[:id])
      if @intline.nil?
          redirect_to root_path
          flash[:danger] = "You don't have rights"
      end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def intline_params
    params.require(:intline).permit(:created_at, :lineName, :ticketN, :remHS, :remOK, :closed_at)
  end
end

app/helpers/intlines_helper.rb
module IntlinesHelper
end

app/views/intlines/_form.html.erb
<%= form_for(@intline) do |f| %>
  <% if @intline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intline.errors.count, "error") %> prohibited this intline from being saved:</h2>

      <ul>
      <% intline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lineName %>
    <%= f.text_field :lineName %>
  </div>

  <div class="field">
    <%= f.label :ticketN %>
    <%= f.text_field :ticketN %>
  </div>

  <div class="field">
    <%= f.label :remHS %>
    <%= f.text_area :remHS %>
  </div>

  <div class="field">
    <%= f.label :userHS %>
    <%= f.text_field :userHS %>
  </div>

  <div class="field">
    <%= f.label :remOK %>
    <%= f.text_area :remOK %>
  </div>

  <div class="field">
    <%= f.label :userOK %>
    <%= f.text_field :userOK %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.time_select :duration %>
  </div>

  <div class="field">
    <%= f.label :panel %>
    <%= f.text_field :panel %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intlines/edit.html.erb
<% provide(:title, 'Edit Report Line') %>


<div class="col-md-6">
  <div class="box box-primary">

		<%= form_for @intline do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		  <div class="box-body">
			  <div class="bootstrap-timepicker">
					<div class="form-group">
				  		<label>Time picker</label>
						<div class="input-group">
							<%= f.text_field :created_at, class:"form-control timepicker" %>
							<div class="input-group-addon">
					  			<i class="fa fa-clock-o"></i>
							</div>
				  		</div>
					</div>
			  	</div>

			  	<div class="form-group">
					<label>Line</label>
					<%= f.text_field :lineName, class:"form-control select2" %>
			  	</div>

				<div class="form-group">
				  <label for="exampleInputPassword1">Ticket Number</label>
				  <%= f.text_field :ticketN, class:"form-control"%>
				</div>

				<div class="form-group">
					<label>Note</label>
					  <div class="box-body pad">
						  <%= f.text_area :remHS, class:"textarea" %>
					  </div>
			  	</div>
			  	<div class="box-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
			  	</div>
			</div>
		<%end%>
	</div>
</div>

app/views/intlines/index.html.erb
<% provide(:title, "Lines") %>
<div style="padding: 8px;width: 200px;float:right;z-index:1;">
<%= link_to 'Report Line', new_intline_path, class: "btn btn-success btn-md" %>
</div>
<%= content_tag :table, class: "table-striped", role: :datatable, data: { url: intlines_path(format: :json) } do %>
  <thead>
    <tr>
      <th>Opened</th>
      <th>Line Name</th>
      <th>Ticket Number</th>
      <th>Note HS</th>
      <th>Added by</th>
      <th>Closed by</th>
      <th>Note OK</th>
      <th>Closed</th>
      <th>Panel</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
<% end %>
<br>

app/views/intlines/new.html.erb
<!-- <%= render 'form', line: @line %> -->
<% provide(:title, 'Report Line') %>


<div class="col-md-6">
  <div class="box box-primary">

		<%= form_for @intline, url: newHSline_path do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		  <div class="box-body">
			  <div class="bootstrap-timepicker">
					<div class="form-group">
				  		<label>Time picker</label>
						<div class="input-group">
							<%= f.text_field :created_at, class:"form-control timepicker" %>
							<div class="input-group-addon">
					  			<i class="fa fa-clock-o"></i>
							</div>
				  		</div>
					</div>
			  	</div>

			  	<div class="form-group">
					<label>Line</label>
                    <!-- <%= f.collection_select :id, Line.all, :id, :name, {:prompt => ' Select Line'}%> -->
					<%= f.select :lineName, @lines.all.map(&:name) , {include_blank: true}, class:"form-control select2" %>
			  	</div>

				<div class="form-group">
				  <label for="exampleInputPassword1">Ticket Number</label>
				  <%= f.text_field :ticketN, class:"form-control"%>
				</div>

				<div class="form-group">
					<label>Note</label>
					  <div class="box-body pad">
						  <%= f.text_area :remHS, class:"textarea" %>
					  </div>
			  	</div>

			  	<div class="box-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
			  	</div>
			</div>
		<%end%>
	</div>
</div>

app/views/intlines/restore.html.erb
<% provide(:title, 'Close Report Line') %>


<div class="col-md-6">
  <div class="box box-primary">

		<%= form_for @intline, url: close_intline_path, html: { method: "patch" }  do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		   <div class="box-body">
					<div class="form-group">
				  		<label>Time picker</label>
                        <div class='input-group date', id='datetimepicker'>
                            <%= f.text_field :closed_at, class:"form-control" %>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>

				    <div class="form-group">
					    <label>Note</label>
					    <div class="box-body pad">
						   <%= f.text_area :remOK, class:"textarea" %>
					    </div>
			  	    </div>
			  	    <div class="box-footer">
					    <button type="submit" class="btn btn-primary">Submit</button>
			  	    </div>
		   </div>
		<%end%>
	</div>
</div>

app/views/intlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Linename:</strong>
  <%= @intline.lineName %>
</p>

<p>
  <strong>Ticketn:</strong>
  <%= @intline.ticketN %>
</p>

<p>
  <strong>Remhs:</strong>
  <%= @intline.remHS %>
</p>

<p>
  <strong>Userhs:</strong>
  <%= @intline.userHS %>
</p>

<p>
  <strong>Remok:</strong>
  <%= @intline.remOK %>
</p>

<p>
  <strong>Userok:</strong>
  <%= @intline.userOK %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @intline.duration %>
</p>

<p>
  <strong>Panel:</strong>
  <%= @intline.panel %>
</p>

<p>
  <strong>User:</strong>
  <%= @intline.user %>
</p>

<%= link_to 'Edit', edit_intline_path(@intline) %> |
<%= link_to 'Back', intlines_path %>